<?php

/**
 * Description of NoticiasController
 *
 * AUTOGENERATED

 * @author Sergio Pérez <sergio.perez@albatronic.com>
 * @copyright Informática ALBATRONIC
 * @date 27-Sep-2014
 *
 */
class NoticiasController extends ControllerProject {

    protected $controller = "Noticias";

}