<?php

/**
 * Description of EnlacesController
 *
 * AUTOGENERATED

 * @author Sergio Pérez <sergio.perez@albatronic.com>
 * @copyright Informática ALBATRONIC
 * @date 06-Dec-2014
 *
 */
class EnlacesController extends ControllerProject {

    protected $entity = "Enlaces";

}
