<?php

/**
 * Description of GaleriaController
 *
 * AUTOGENERATED

 * @author Sergio Pérez <sergio.perez@albatronic.com>
 * @copyright Informática ALBATRONIC
 * @date 27-Sep-2014
 *
 */
class GaleriaController extends ControllerProject {

    protected $controller = "Galeria";

}